import { StyleSheet } from "react-native";
import { Fonts } from "../../utils/constants/fonts";

const styles=StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    container2:{
        justifyContent:'center',
        alignItems:'center',
        paddingHorizontal:20,
    },
    header:{
        fontSize:24,
        fontFamily:Fonts.AtmaBold,
    },
    subHeader:{
        fontSize:16,
        fontFamily:Fonts.AtmaRegular,
    },
    formContainer:{
        marginTop:20,
    },
    inputContainer:{
        marginBottom:10,
    },
    inputLabel:{
        fontSize:16,
        fontFamily:Fonts.AtmaRegular,
    },
    input:{
        width:300,
        height:40,
        borderColor:'gray',
        borderWidth:1,
        borderRadius:20,
        paddingHorizontal:10,
    },
    passwordContainer:{
        width:300,
        height:40,
        borderColor:'gray',
        borderWidth:1,
        borderRadius:20,
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:10,
    },
    passwordInput:{
        flex:1,
        height:'100%',
    },
    eyeButton:{
        paddingHorizontal:6,
        justifyContent:'center',
        alignItems:'center',
    },
    eyeIcon:{
        fontSize:18,
    },
    button:{
        marginTop:20,
        width:300,

        height:40,
        backgroundColor:'gold',
        borderRadius:20,
        justifyContent:'center',
        alignItems:'center',
    },
    buttonText:{
        color:'white',
        fontSize:16,
        fontFamily:Fonts.AtmaBold,
    },
})
export default styles